apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: 3000
    nodePort: 32136
  externalIPs:
    -  13.233.192.35
